services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT:-8080}:80
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
  db:
    image : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  app:
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - ${APP_PORT:-9001}:9000
      - ${VITE_PORT:-5173}:5173
    working_dir: /var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-3400}:80
    depends_on:
      - db
networks:
  accounts:
    name: account-network
    driver: bridge