openapi: 3.0.0
info:
  title: Account (users) service
  description: API for account services
  version: 0.1.9
servers:
  - url: /api

paths:
  /users:search:
    post:
      tags:
        - Users
      summary: Get users list or filter it
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchResourceRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UsersResponse'
        '401':
          description: Unauthorized
  /users:
    post:
      tags:
        - Users
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/users.yaml#/UserUpdateOrCreateRequest'
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by id
      description: Get user by id
      parameters:
        - $ref: '#/components/parameters/PathId'
        - $ref: '#/components/parameters/QueryInclude'
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
        '400':
          description: Bad request
        500:
          description: Server error
    delete:
      tags:
        - Users
      summary: Delete user by id
      description: Delete user by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: User Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResource'
        '400':
          description: Bad request
        500:
          description: Server error
    patch:
      tags:
        - Users
      summary: Update user by id
      description: Update user by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/users.yaml#/UserUpdateOrCreateRequest'
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: './schemas/users.yaml#/UserResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PathId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: Числовой id
      example: 1
    QueryInclude:
      in: query
      name: include
      required: false
      description: Relationships
      schema:
        type: string
  schemas:
    EmptyResource:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
    SearchResourceRequest:
      type: object
      properties:
        filter:
          type: object
          properties:
            name:
              type: string
        include:
          type: array
        sort:
          type: array
